import dynamic from "next/dynamic";
import { CodeBlock } from "@/components/docs/CodeBlock";
import { t } from "@/locales";
import { FLAGSHIP_CODE } from "./generatedCode";
import { SectionHeading } from "./SectionHeading";

// Below-the-fold, so its client chunk splits off the hero's critical path
// instead of loading eagerly with it. ssr: true (the only option Next allows
// for a dynamic import inside a Server Component anyway) — the wizard still
// renders on the server, so there's no first-paint layout shift once the
// chunk streams in. `loading` only shows on a client-side chunk fetch,
// which SSR normally preempts.
const FlagshipSignupForm = dynamic(
  () => import("./FlagshipSignupForm").then((mod) => mod.FlagshipSignupForm),
  {
    ssr: true,
    loading: () => (
      <p role="status" className="text-[13px] tablet:text-[13px] desktop:text-[13px] text-muted-foreground">
        {t.home.flagship.previewLoading}
      </p>
    ),
  },
);

/**
 * The signature section: one editor-window frame around the real multi-step
 * signup wizard and the exact code its config serializes to (FLAGSHIP_CODE,
 * generated by the builder's own toTs, see generatedCode.ts). The mono tab
 * bar is chrome, not a functional switcher — both panes render at once, side
 * by side on desktop and stacked (code above preview) on tablet/mobile — so
 * this stays a Server Component; FlagshipSignupForm (components/home/
 * FlagshipSignupForm.tsx) is the only client leaf. That wrapper — not
 * app/(site)/examples/multi-step-signup/SignupExampleForm — is deliberate:
 * SignupExampleForm pulls in ExampleForm's registerBuiltInFields() (all 24
 * field renderers) for a config that only needs 3; FlagshipSignupForm
 * scope-registers just those and imports multiStepSignupConfig + the OTP
 * stubs directly from the /examples route (no config duplication, no real
 * network — see that component's own comments).
 */
export function FlagshipSplit() {
  return (
    <section
      aria-labelledby="flagship-heading"
      className="flex flex-col gap-[16px] tablet:gap-[16px] desktop:gap-[16px] pb-[64px] tablet:pb-[96px] desktop:pb-[120px]"
    >
      <SectionHeading id="flagship-heading" center={false}>
        {t.home.flagship.title}
      </SectionHeading>
      <p className="text-[14px] tablet:text-[14px] desktop:text-[14px] text-muted-foreground">
        {t.home.flagship.intro}
      </p>
      <div className="rounded-[16px] tablet:rounded-[16px] desktop:rounded-[16px] border border-border bg-card overflow-hidden">
        <div className="flex items-center gap-[2px] tablet:gap-[2px] desktop:gap-[2px] border-b border-border px-[10px] tablet:px-[10px] desktop:px-[10px] pt-[8px] tablet:pt-[8px] desktop:pt-[8px]">
          <span className="rounded-t-[6px] tablet:rounded-t-[6px] desktop:rounded-t-[6px] border border-b-0 border-border bg-background px-[10px] tablet:px-[10px] desktop:px-[10px] py-[6px] tablet:py-[6px] desktop:py-[6px] text-[12px] tablet:text-[12px] desktop:text-[12px] font-mono text-foreground">
            {t.home.flagship.codeTabLabel}
          </span>
          <span className="rounded-t-[6px] tablet:rounded-t-[6px] desktop:rounded-t-[6px] px-[10px] tablet:px-[10px] desktop:px-[10px] py-[6px] tablet:py-[6px] desktop:py-[6px] text-[12px] tablet:text-[12px] desktop:text-[12px] font-mono text-muted-foreground">
            {t.home.flagship.previewTabLabel}
          </span>
        </div>
        <div className="grid grid-cols-1 desktop:grid-cols-2">
          <div className="border-b desktop:border-b-0 desktop:border-r border-accent-brand p-[20px] tablet:p-[20px] desktop:p-[24px]">
            <h3 className="sr-only">{t.home.flagship.codeHeading}</h3>
            <CodeBlock
              code={FLAGSHIP_CODE}
              label={t.home.flagship.codeAriaLabel}
              className="max-h-[420px] tablet:max-h-[420px] desktop:max-h-[480px] overflow-y-auto"
            />
          </div>
          <div className="p-[20px] tablet:p-[20px] desktop:p-[24px]">
            <h3 className="sr-only">{t.home.flagship.previewHeading}</h3>
            <FlagshipSignupForm />
          </div>
        </div>
      </div>
    </section>
  );
}
