import { registerField } from "../core/registry";
import { CheckboxField } from "./CheckboxField";
import { CountryField } from "./CountryField";
import { DateField } from "./DateField";
import { FileField } from "./FileField";
import { GroupField } from "./GroupField";
import { HiddenField } from "./HiddenField";
import { OtpField } from "./OtpField";
import { PhoneField } from "./PhoneField";
import { RadioField } from "./RadioField";
import { RatingField } from "./RatingField";
import { SegmentedField } from "./SegmentedField";
import { SelectField } from "./SelectField";
import { SliderField } from "./SliderField";
import { StaticField } from "./StaticField";
import { SubmitField } from "./SubmitField";
import { TextField } from "./TextField";
import { TimeField } from "./TimeField";

export function registerBuiltInFields(): void {
  registerField("text", TextField);
  registerField("email", TextField);
  registerField("password", TextField);
  registerField("textarea", TextField);
  registerField("number", TextField);
  registerField("checkbox", CheckboxField);
  registerField("switch", CheckboxField);
  registerField("radio", RadioField);
  registerField("segmented", SegmentedField);
  registerField("select", SelectField);
  registerField("country", CountryField);
  registerField("otp", OtpField);
  registerField("phone", PhoneField);
  registerField("date", DateField);
  registerField("time", TimeField);
  registerField("rating", RatingField);
  registerField("slider", SliderField);
  registerField("file", FileField);
  registerField("group", GroupField);
  registerField("hidden", HiddenField);
  registerField("static", StaticField);
  registerField("submit", SubmitField);
}
